version: "3.3"

services:
 tidyverse:
    restart: always
    image: rocker/tidyverse
    container_name: rstudio
    ports:
      - "8787:8787"
    environment:
      - USER=test
      - PASSWORD=test
    volumes:
      - "/home/ubuntu/Dropbox:/home/rstudio"
 
 shiny:
    restart: always
    image: rocker/shiny
    container_name: shiny
    ports:
      - "3838:3838"

volumes:
  data-volume:
