version: "3.3"

services:
 tidyverse:
    restart: always
    image: rocker/tidyverse
    container_name: rstudio
    port:
      - "8787:8787"
    environment:
      - USER=test
      - PASSWORD=test

 shiny:
    restart: always
    image: rocker/shiny
    container_name: shiny
    port:
      - "3838:3838"

volumes:
  data-volume:
